name: Test and Lint

on:
    pull_request:
        branches:
            - "**"

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   uses: actions/setup-node@v2
                with:
                    node-version: 16
                    cache: 'yarn'
            -   run: yarn
            -   run: yarn nx affected:lint --base=origin/main --parallel
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   uses: actions/setup-node@v2
                with:
                    node-version: 16
                    cache: 'yarn'
            -   run: yarn
            -   run: yarn nx affected:test --base=origin/main --parallel
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   uses: actions/setup-node@v2
                with:
                    node-version: 16
                    cache: 'yarn'
            -   run: yarn
            -   run: yarn nx affected:build --base=origin/main --parallel --production
