name: Test and Lint

on:
    push:
        branches:
            - 'main'

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   uses: actions/setup-node@v2
                with:
                    node-version: 16
                    cache: 'yarn'
            -   run: yarn
            -   run: yarn nx affected:lint --parallel
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   uses: actions/setup-node@v2
                with:
                    node-version: 16
                    cache: 'yarn'
            -   run: yarn
            -   run: yarn nx affected:test --parallel
    publish:
        runs-on: ubuntu-latest
        needs:
            - lint
            - test
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   uses: actions/setup-node@v2
                with:
                    node-version: 16
                    cache: 'yarn'
            -   name: git config
                run: |
                    git config user.name "${GITHUB_ACTOR}"
                    git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            -   run: yarn
            -   run: yarn nx affected --target=bump-version --parallel --push
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   name: build
                run: yarn nx affected:build --parallel --production

            -   run: echo _auth=${{ secrets.NPM_PUBLSH_KEY }} >> .npmrc
            -   run: echo email=${{ secrets.NPM_PUBLSH_EMAIL }}  >> .npmrc
            -   run: echo always-auth=true >> .npmrc
            -   name: publish
                run: yarn nx affected --target=publish-npm --parallel
